Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [60]:
import numpy as np
N = 10
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [63]:
N = 10
a = np.diag(np.arange(N-1, -1, -1), k=0)
a # выводим матрицу

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [65]:
# Считаем сумму значений на диагонали
total_sum = 0
for i in range(len(a)):
    total_sum+=a[i][i]
print(total_sum)

45


Задание 3. Решите систему уравнений:

\begin{equation*}
\LARGE
4*x + 2*y + z = 4 \\
\LARGE
x + 3*y = 12 \\
\LARGE
5*y + 4*z = -3
\end{equation*}

In [73]:
left = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) # левая часть уравнения
right = np.array( [4, 12, -3] ) # правая часть уравнения
from numpy import linalg
# решение уравнения
linalg.solve(left, right)

array([ 0.46666667,  3.84444444, -5.55555556])

In [74]:
# проверка верности решения уравнения
np.allclose( np.dot(left, linalg.solve(left, right)), right )

True